application:
  swagger:
    enabled: true
    title: Сервис rosalko-adapter
    description: Описание API сервиса rosalko-adapter
    version: 1.0.0
  monitor:
    enabled: true
    rest:
      incoming: true
      outgoing: true
      showBody: true
      showHeader: true
      showCookie: false
  logs:
    amqp:
      uri: amqp://amq:amq@localhost:5672
      key: logs.local

server:
  port: 8080
  servlet:
    context-path: /rosalko-adapter

spring:
  application:
    name: rosalko-adapter
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://uidm.uidm-dev.d.exportcenter.ru/sso/oauth2/tokeninfo
#            introspection-uri: https://lk.t.exportcenter.ru/sso/oauth2/tokeninfo
      client:
        registration:
          uidm:
            client-id:
            client-secret:
            authorization-grant-type: client_credentials
        provider:
          uidm:
            token-uri: http://uidm.uidm-dev.d.exportcenter.ru/sso/oauth2/access_token
#            token-uri: https://lk.t.exportcenter.ru/sso/oauth2/access_token

springdoc:
  swagger-ui:
    enabled: true
  packages-to-scan: ru.seventech

transformer:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

pass-error-trace: true



storage-url:
  base-url: http://localhost:8082/docstore