application:
  swagger:
    enabled: true
    title: Сервис rosalko-adapter
    description: Описание API сервиса rosalko-adapter
    version: 1.0.0
  monitor:
    enabled: true
    rest:
      incoming: true
      outgoing: true
      showBody: true
      showHeader: true
      showCookie: false

server:
  port: 8080
  servlet:
    context-path: /rosalko-adapter

spring:
  application:
    name: rosalko-adapter
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri:
      client:
        registration:
          uidm:
            client-id:
            client-secret:
            authorization-grant-type: client_credentials
        provider:
          uidm:
            token-uri:

springdoc:
  swagger-ui:
    enabled: true
  packages-to-scan: ru.seventech

pass-error-trace: true

rosalko:
  html-page-url: https://fsrar.gov.ru/opendata/7710747640-reestr

ivis:
  web:
    url: https://licreestr.fsvps.ru/api/license-rec
    username:
    password:
  caches:
    farma:
      sphere: 1
      capacity: 1_000
    medical:
      sphere: 2
      capacity: 20_000

storage-url:
  download-url: /api/v2/

webclient:
  http:
    connect-timeout: 10000    # 10 секунд
    response-timeout: 1800000 # 30 минут





